#!/usr/bin/env bash

set -e

if ! command -v uv 2>&1 >/dev/null; then
  "uv not installed."
  exit 1
fi

cd "$(dirname "$0")/.."

if [ -z "${VIRTUAL_ENV}" ]; then
  uv venv venv
  source venv/bin/activate
fi

uv sync --active --group dev
pre-commit install
